CREATE TYPE txn_status;

CREATE OR REPLACE FUNCTION txn_status_out(status txn_status)
RETURNS CSTRING AS 'MODULE_PATHNAME'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION txn_status_in(status CSTRING)
RETURNS txn_status AS 'MODULE_PATHNAME'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE OR REPLACE FUNCTION txn_status_eq(arg1 txn_status, arg2 txn_status)
RETURNS BOOL AS 'MODULE_PATHNAME'
LANGUAGE C STRICT IMMUTABLE PARALLEL SAFE;

CREATE TYPE txn_status (
	INPUT = txn_status_in,
	OUTPUT = txn_status_out,
	INTERNALLENGTH = 1,
    PASSEDBYVALUE,
    ALIGNMENT = char
);

CREATE OPERATOR = (
	LEFTARG = txn_status,
	RIGHTARG = txn_status,
	PROCEDURE = txn_status_eq
);
